# Generated by Django 3.0.4 on 2020-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodatabase',
            name='description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
